### ISSUE TITLE
Именование обработчиков событий

### ISSUE THREAD

**Issue by Frolikow** [MorganaLF/FlatUI#13]
Обработчики событий следует именовать по шаблону `handleElementNameEventName`
Например вместо: 
```javascript
    $geolocationButton.on(
      `click.mapDefineGeolocation${this.elementIndex}`,
      this._defineGeolocation.bind(this),
    );
```
Должно быть:
```javascript
    $geolocationButton.on(
      `click.mapDefineGeolocation${this.elementIndex}`,
      this.handleGeolocationButtonClick.bind(this),
    );
```
Это нужно, чтобы не придумывать лишний раз имя для колбэка, так гораздо нагляднее что это именно обработчик события. Пройди по всему проекту. 

И на слайдере тоже можешь создать ишью и сделать правки.

**Comment by MorganaLF** [comment]
А если, например, у меня один и тот же обработчик на разные события, то как тогда его именовать?

И сразу здесь же спрошу по поводу неймспейсов для событий: в стандартах написано, что они должны быть уникальны для инстанса каждого класса, мне ничего больше не придумалось, кроме как передать туда индекс элемента, для которого создается инстанс класса)) Хотелось  бы узнать, как это должно быть реализовано по-нормальному.

**Comment by Frolikow** [comment]
> А если, например, у меня один и тот же обработчик на разные события, то как тогда его именовать? 

В таком случае правильнее будет именовать как я описывал раньше, и уже в каждом из полученных обработчиков  вызывать эту функцию

> И обратная ситуация

в этом случае, вообще странно, почему два обработчика подряд на одно и тоже событие. Будет правильнее объединить обработчики в один 

> И сразу здесь же спрошу по поводу неймспейсов для событий: в стандартах написано, что они должны быть уникальны для инстанса каждого класса, мне ничего больше не придумалось, кроме как передать туда индекс элемента, для которого создается инстанс класса)) Хотелось бы узнать, как это должно быть реализовано по-нормальному.

на счет этого попозже дам развернутый ответ

**Comment by Frolikow** [comment]
Собственно на счет развернутого ответа...)
Его к сожалению не будет) т.к. я ошибочно предположил что эту тему можно сильно развернуть и использовать разные приемы для задания уникальности

С задачей, твое решение справляется, также как вариант, как писал Алексей (в [21 ишью](https://github.com/MorganaLF/FlatUI/issues/21) ), можно использовать хеши.
А изобретать какой-то _велосипед_ я считаю неоправданным) 
Вот и весь ответ)

**Comment by alextsk** [comment]
> также как вариант, как писал Алексей 

не совсем так же, в моем варианте объект должен сам хранить свои события, в текущем нужно хранить их в отдельной структуре после создания или знать в какой последовательности создавались объекты. и не факт что они всегда создаются в одном порядке.

но в целом раз решение есть, закрываем ишью, @Frolikow ?

**Comment by Frolikow** [comment]
Да, думаю закрываем)
