### ISSUE TITLE
Active inputs

### ISSUE THREAD

**Issue by alextsk** [MorganaLF/FlatUI#14]
![image](https://user-images.githubusercontent.com/16453186/57303034-a3998300-7106-11e9-868d-e927b4e1bb28.png)

Error и thanks не висят постоянно, это реакция инпутов на ввод

то же в 
![image](https://user-images.githubusercontent.com/16453186/57303156-ea877880-7106-11e9-8cec-6ac166333683.png)
 красная плашка должна появляться после нажатия на поиск

![image](https://user-images.githubusercontent.com/16453186/57303277-2cb0ba00-7107-11e9-9435-b2aa17683225.png)
остается открытым после выбора опции

а вот 
![image](https://user-images.githubusercontent.com/16453186/57303418-7ac5bd80-7107-11e9-9715-c55b0bafe35f.png)
не инпут, это индикатор(как пай чарт) и он не интерактивен)

**Comment by MorganaLF** [comment]
> не инпут, это индикатор(как пай чарт) и он не интерактивен)

А можно хотя бы на странице "Get started" оставить его интерактивным? А то там всю страницу переделывать придется)

**Comment by alextsk** [comment]
я посмотрел  в его код, там все равно переписывать) почему компонент вообще знает про scrollCarousel? даже если он активный, этот код должен с ним общаться снаружи. 
мне кажется проще сделать его обычным, и переключать модификаторами. а транзишн повесить на стрелочные кнопки например
код должен быть на сайте, не в кнопках)

**Comment by MorganaLF** [comment]
> красная плашка должна появляться после нажатия на поиск

А как это реализовать, если по идее после нажатия на кнопку поиска происходит переход на страницу результатов поиска и данное состояние мы никогда не увидим?

**Comment by alextsk** [comment]
здесь просто показывать ее на клик на иконке и убирать при фокусе в поле инпута. как это в реальности дожно работать пока не важно, мы же не подключаем бэк. но в теории можно  подтягивать результаты динамически, если их нет выводить ошибку

**Comment by alextsk** [comment]
зря я в код не посмотрел сначала)
в общем, это все разные компоненты, есть инпут, есть текстареа, только компонента "форма" нет, есть просто тэг форма и в нем все инпуты и кнопки. 
логично, что в каждом инпуте есть оба состояния.

не помню деталей, но я делал это без js, можно посмотреть у меня в репозитории 

пс: понимаешь почему форма не компонент?

**Comment by MorganaLF** [comment]
> пс: понимаешь почему форма не компонент?

Честно говоря, нет) Она ведь может переиспользоваться и у меня сейчас получилось очень много копипасты после удаления блока формы.

**Comment by alextsk** [comment]
если взять случайную форму, какова вероятность что она будет использована заново с тем же количеством и типом полей и кнопок  и например разными лейблами? 
я не могу представить такой юзкейс даже для самого простого набора, не будет на сайте трех форм логина.
может у тебя есть идеи как она может переиспользоваться?

**Comment by MorganaLF** [comment]
> может у тебя есть идеи как она может переиспользоваться?

Ну не знаю, одна и та же контактная форма, например, может встретиться несколько раз на лендинге)

**Comment by MorganaLF** [comment]
По этому ишью все исправлено, можно проверить.

**Comment by alextsk** [comment]
stage точно можно упростить, там столько условий, я не понимаю что происходит) это же самый простой компонент

**Comment by MorganaLF** [comment]
Stage исправлено

**Comment by alextsk** [comment]
```
    if (i === 1)
      .stage__item
        span.stage__item-text= i
```
может просто вынести это из цикла?

**Comment by MorganaLF** [comment]
> может просто вынести это из цикла?

Исправлено
