### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by alextsk** [MorganaLF/FlatUI#15]
![image](https://user-images.githubusercontent.com/16453186/57303667-02133100-7108-11e9-9270-631cb61122b2.png)

почему subheading? где supheading?)
и почему один h1 другой h2? на вид они все на одном уровне

**Comment by alextsk** [comment]
они могут быть все h1 по одному на секцию, если иерархически секции на верхнем уровне и не связаны, думаю тут как раз такой случай

**Comment by MorganaLF** [comment]
Вот здесь в стандартах написано, что на всю страницу h1 может быть только один раз:

![1234](https://user-images.githubusercontent.com/38564412/57312344-00407200-70f6-11e9-9369-13368a5493fa.png)

Тогда, наверное, тут какое-то уточнение надо добавить про то, что могут быть исключения.

**Comment by alextsk** [comment]
да, там похоже устаревшие данные, до хтмл5 так было

**Comment by alextsk** [comment]
что если в tag передать p например? или script ) та же проблема что с интерполяцией классов, то же решение. и раз можно выбирать варианты, то наверно это не всегда main?
