### ISSUE TITLE
Arrow button

### ISSUE THREAD

**Issue by alextsk** [MorganaLF/FlatUI#16]
https://github.com/MorganaLF/FlatUI/blob/1d3d1d7a9e5a53bbb4ac97544aa2143dd2cf029c/src/components/arrow-button/arrow-button.pug#L5-L7
интерполяция переменных, то же, что в первом задании
посмотри в других тоже, может это пробема не только стрелок, я просто с них начал

кстати, свгшки тут уместны в компоненте, они его часть логически, но для них сделан блок, а блок должен быть самодостаточен. я думаю без него можно обойтись, как и без лишних картинок, свг отлично стилизуется в css если его инлайнить

**Comment by MorganaLF** [comment]
Исправлено.

**Comment by alextsk** [comment]
https://github.com/MorganaLF/FlatUI/blob/cb797d29ebc8ffdebc8441e1397add72680d0058/src/components/ui-kit-components/user/user.pug#L34

для итерации лучше использовать each

https://github.com/MorganaLF/FlatUI/blob/cb797d29ebc8ffdebc8441e1397add72680d0058/src/components/ui-kit-components/user/user.pug#L42-L48

 это кандидат на переезд в объект

**Comment by MorganaLF** [comment]
> не понимаю, когда есть цвет в списке ставим белый? secondary зачем тогда?

Ну дефолтный бэкграунд серый, на нем цвет текста красно-черный. 
А если бэкграунд цветной (secondary или может primary впоследствии добавится), то нам нем уже цвет текста белый.

**Comment by alextsk** [comment]
я про то как это используется,  тут `user__info_${backgrounds[backgroundColor]}` он участвует в имени класса, почему в остальных white? что если secondary aliceblue?)

**Comment by alextsk** [comment]
`const sizes = { ` а в макете разве есть варианты размера?

**Comment by MorganaLF** [comment]
> const sizes = { а в макете разве есть варианты размера?

Здесь мне понадобились варианты размера для демо-сайта)

**Comment by alextsk** [comment]
тогда надо как то более элегантно это решать) вообще если для разбора конфига нужен тернарник - очень вероятно что-то не то с конфигом, должно быть типа `class = conf[size].iconMod `и все, без склеек без условий. максимум `|| ""`

**Comment by MorganaLF** [comment]
А почему тернарники плохо? В этой статье все как раз на тернарниках сделано:

https://fullstack-development.gitbook.io/learn/komponentnaya-arkhitektura#chto-takoe-preprocessory

А здесь если сделать через `|| ""` то в случае отсутствия модификатора останется `"user_"`

**Comment by alextsk** [comment]
> А почему тернарники плохо?
а они не плохо, плохо когда нужны условия при разборе конфига, и куча склеек. тут мог быть if с тем же успехом

лучае отсутствия модификатора останется "user_" - если хранить кусками то да)

**Comment by MorganaLF** [comment]
> это кандидат на переезд в объект

Не совсем поняла, нужно сделать хэшмап? Тогда ведь не получится динамически инклюдить svg, а помещать весь код svg в миксин не хочется.

**Comment by alextsk** [comment]
>  получится динамически инклюдить svg

да, были у меня сомнения. а точно инклюд не принимает переменные?

**Comment by MorganaLF** [comment]
> да, были у меня сомнения. а точно инклюд не принимает переменные?

Я так поняла, что не принимает, я здесь нашла решение, которое у себя в миксине использовала: https://github.com/pugjs/pug/issues/2030

**Comment by alextsk** [comment]
поискал, есть варианты но не идеальные. просто смысла нет в цикле, case не масштабируется. 
в этом случае я за хардкод
https://github.com/alextsk/blog-markup/blob/master/src/components/profile/profile.pug
посмотри, может пригодится

**Comment by MorganaLF** [comment]
Блок user исправлен. Вроде бы получше стало)

**Comment by alextsk** [comment]
значительно получше)
почему grey а не primary?

**Comment by MorganaLF** [comment]
> почему grey а не primary?

Ну primary у меня красный, secondary зеленый, а серый он всегда серый, я так понимаю) То есть если будет меняться цветовая схема сайта, то красный и зеленый могут быть заменены на другие цвета, а серые-белые-черные цвета останутся.

**Comment by alextsk** [comment]
> серые-белые-черные цвета останутся? 

не факт, текст например можно набрать вывороткой, и черные с белыми поменяются. 
поэтому плохая идея называть модификаторы по цвету типа _red, может он мажента или терракотовый)
к тому же рядом с ним secondary, серый может тогда neutral?

**Comment by MorganaLF** [comment]
Да, neutral подходит) Исправила

**Comment by alextsk** [comment]
мы как то упустили тот факт, что это модификатор, а у блока должен быть цвет по умолчанию, вот он и есть neutral) а в модификаторах все таки должен быть primary, secondary без него странно выглядит

**Comment by MorganaLF** [comment]
Исправлено

**Comment by alextsk** [comment]
теперь primary стал серым, я не об этом, серый должен быть по умолчанию, без модификатора. а праймари такой же как везде

**Comment by MorganaLF** [comment]
> а праймари такой же как везде

Но тут в этом блоке по макету праймари вообще нет. 

И еще вопрос. Если сделать по умолчанию серый, то получается, в таком случае блок с серым бэкграундом идет без модификатора вовсе. А если он идет без модификатора, то появляется необходимость использовать тернарник в классе, поскольку `class=backgrounds[backgroundColor].infoMod || ""` работать не будет, т.к. backgrounds[backgroundColor] не существует.

**Comment by alextsk** [comment]
secondary: { infoMod: "user__info_secondary" } - и тут не нужна наверно доп структура, если там всегда один элемент можно просто `secondary: "user__info_secondary" `

**Comment by alextsk** [comment]
> серым бэкграундом идет без модификатора вовсе

так  и есть

без опции может работать например так 
`class=backgrounds[backgroundColor] && backgrounds[backgroundColor].infoMod`
но если структура плоская то и это не понадобится

> использовать тернарник в классе

это не то чтобы прям совсем ужас, просто если можно без них лучше без них

**Comment by MorganaLF** [comment]
Значит, у меня и с модификатором size та же ошибка, то, что я сделала small, должно было быть по умолчанию. Переделала.

**Comment by alextsk** [comment]
думаю юзер готов)
я это ишью закрою, далековато уже ушли от Arrow button) 
посмотри есть ли проблемы которые были в user в других компонентах, если найдешь можно исправить без ишью. или свое создать.
