### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by alextsk** [MorganaLF/FlatUI#17]
![image](https://user-images.githubusercontent.com/16453186/57306209-9da6a080-710c-11e9-9751-e9f281b5d48f.png)
превышение пдк container ов)

**Comment by MorganaLF** [comment]
Исправлено.

**Comment by alextsk** [comment]
деплой не делала после изменений?

**Comment by MorganaLF** [comment]
Наверное, забыла, сейчас точно сделала)
