### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by Frolikow** [MorganaLF/FlatUI#19]
При нажатии на кнопку `TODAY`, перестает работать метод `_handleDayButtonClick`. Нужно починить. Заодно мб получиться избавиться от повторного навешивания обработчика 
```javascript
    $dayButton
      .on(
        `click.calendarResizeFont${this.elementIndex}`,
        this._handleDayButtonClick.bind(this),
      );
```
И еще при поочередном нажатии на любую дату и кнопку `TODAY`, меняются шрифты в элементе `calendar__body`

**Comment by MorganaLF** [comment]
> Заодно мб получиться избавиться от повторного навешивания обработчика

Здесь наоборот пришлось то же самое сделать, поскольку плагин после каждого клика всё перерисовывает, элементы, на которые навешивались обработчики, удаляются, и их приходится заново навешивать.

**Comment by Frolikow** [comment]
Странно, что при таких условиях один обработчик отваливается, а остальные спокойно живут.
Пока ишью закрою, но еще подумаю из-за чего удаляется обработчик

**Comment by MorganaLF** [comment]
> Странно, что при таких условиях один обработчик отваливается, а остальные спокойно живут

Отваливаются обработчики, которые навешиваются внутри таблицы с числами. Эта таблица плагином удаляется полностью после каждого клика.

Обработчики на футере не отваливаются, поскольку футер рисует не плагин, а я добавила, он лежит вне родного календаря. 

Еще не отваливаются обработчики на стрелках вперед-назад, вот на них не знаю, почему, это уже родные стрелки календаря)
