### ISSUE TITLE
Classes

### ISSUE THREAD

**Issue by alextsk** [MorganaLF/FlatUI#20]
класс должен быть в отдельном файле с тем же названием, а инстанцироваться, соответсвенно, в другом

как минимум в Button не так, может еще есть

**Comment by MorganaLF** [comment]
> класс должен быть в отдельном файле с тем же названием, а инстанцироваться, соответсвенно, в другом

А файл, в котором он инстанцируется, должен лежать так же в папке компонента? Или это должен быть один общий файл на весь проект?

**Comment by alextsk** [comment]
у компонента конечно

**Comment by MorganaLF** [comment]
Исправлено.

**Comment by alextsk** [comment]
классы же называем с большой буквы, к файлам это тоже относится. чтобы сразу было понятно что там лежит.

**Comment by MorganaLF** [comment]
Исправлено
