### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by alextsk** [MorganaLF/FlatUI#21]
https://github.com/MorganaLF/FlatUI/blob/a5ede0d5da8d7ccc4da18bf1c15b1543de1ee539/src/components/ui-kit-components/map/map.js#L49

https://github.com/MorganaLF/FlatUI/blob/a5ede0d5da8d7ccc4da18bf1c15b1543de1ee539/src/components/ui-kit-components/map/map.js#L56

можешь рассказать что здесь происходит?

**Comment by MorganaLF** [comment]
> можешь рассказать что здесь происходит?

Я вот в этом ишью задавала вопрос по этому поводу, пока что не знаю, как это исправить: https://github.com/MorganaLF/FlatUI/issues/13

**Comment by alextsk** [comment]
> быть уникальны для инстанса каждого класса

можешь ссылку кинуть где это в стандартах?

**Comment by MorganaLF** [comment]
https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/jQuery.md

> Выше было требование, что все обработчики должны быть отименованы. Тут это принимает еще более строгий характер — имена обработчиков для разных инстансов одного и того же класса должны быть уникальными, чтобы $(block).off(...) отключал события только для текущего инстанса блока, не для всех инстансов

**Comment by alextsk** [comment]
когда я сдавал этого не было
тогда да, твой вариант рабочий. навскидку можно сгенерировать хеш при инте и вернуть карту (по аналогии с таймерами только у тебя будет несколько значений) но я не буду этого требовать, по желанию
я тут закрою тогда, а в том ишью посмотрим, мне тоже интересно развернутый ответ)
