### ISSUE TITLE
Calendar2

### ISSUE THREAD

**Issue by alextsk** [MorganaLF/FlatUI#22]
https://github.com/MorganaLF/FlatUI/blob/9455c9fdcc588cf3f083080951b8fee1639b54c1/src/components/ui-kit-components/calendar/calendar.pug#L3
01?

https://github.com/MorganaLF/FlatUI/blob/9455c9fdcc588cf3f083080951b8fee1639b54c1/src/components/ui-kit-components/calendar/init.js#L4
почему body?

https://github.com/MorganaLF/FlatUI/blob/9455c9fdcc588cf3f083080951b8fee1639b54c1/src/components/ui-kit-components/calendar/Calendar.js#L122-L134
откуда эти волшебные числа?

https://github.com/MorganaLF/FlatUI/blob/9455c9fdcc588cf3f083080951b8fee1639b54c1/src/components/ui-kit-components/calendar/Calendar.js#L65
зачем? 

https://github.com/MorganaLF/FlatUI/blob/9455c9fdcc588cf3f083080951b8fee1639b54c1/src/components/ui-kit-components/calendar/Calendar.js#L36
calendarResizeFont?

зачем его увеличивать?

почему так много всего происходит? это же jquery-datapicker, у него есть апи, просто нужно было добавить шапку и футер)

**Comment by MorganaLF** [comment]
> 01?

Ну здесь js-ом дата выводится, можно наверное просто оставить пустой див)

> почему body?

Разбила блок календаря на элементы header, body и footer.

> откуда эти волшебные числа?
calendarResizeFont?
зачем его увеличивать?

В изначальном виде календарь совсем не резинится, я сделала, чтобы цифры календаря при любом размере были пропорциональны его ширине.

А на клике висит этот обработчик, поскольку после клика плагин jquery-datapicker перерисовывает все элементы и размер шрифта возвращается к изначальному.

**Comment by alextsk** [comment]
>  совсем не резинится,

 а должен? может я новые задания опять пропустил, но он никогда не резинился

> Разбила блок календаря на элементы header, body и footer.
 
это я видел, я про то, что внешний код не должен знать устройство компонента

**Comment by MorganaLF** [comment]
В задании в требованиях к верстке написано, что

> Все страницы должны быть по максимуму responsive

Я так поняла, что значит, всё должно тянуться.

**Comment by MorganaLF** [comment]
> это я видел, я про то, что внешний код не должен знать устройство компонента

То есть поиском по элементам компонента тоже нельзя пользоваться? А как тогда получать к ним доступ?

**Comment by alextsk** [comment]
> элементам компонента тоже нельзя пользоваться

а почему этого не делать внутри класса?

**Comment by alextsk** [comment]
> Все страницы должны быть по максимуму responsive

> Я так поняла, что значит, всё должно тянуться.

не, это значит при изменении размеров экрана лэйаут себя адекватно ведет, ничего друг на друга не наезжает, если есть много места- заполняется в доп колонку, если места нет то переносится. тянутся текстовые блоки, немного картинки, если разрешения хватает. но виджеты тянуть точно не нужно

**Comment by MorganaLF** [comment]
Исправлено
