### ISSUE TITLE
стили блока drop down

### ISSUE THREAD

**Issue by Frolikow** [MorganaLF/FlatUI#3]
Немного расхождения с макетом.
У тебя при фокусе на дд, сам элемент тоже фон меняет : 
![image](https://user-images.githubusercontent.com/25764783/56457876-243c4d80-63ab-11e9-98c7-3aba683845d7.png)
а в макете:
![image](https://user-images.githubusercontent.com/25764783/56457880-2e5e4c00-63ab-11e9-96fa-c7854c77de46.png)

**Comment by MorganaLF** [comment]
Если честно, я немного запуталась здесь, поскольку в стандартах написано, что если у элемента указывается outline: none, то обязательно прописывать стили для фокуса. Но тут по макету получается, что и при фокусе, и не в фокусе элемент одинаково выглядит, а значит, при перемещении по странице табами не будет видно, когда он в фокусе. Поэтому я добавила фон для фокуса. Если же просто оставить дефолтный outline, то вообще крайне странно выглядит.

**Comment by alextsk** [comment]
это нормально, если в макете нет варианта фокуса то лучше свой чем никакого. 
фокус здесь вполне прилично выглядит, чтобы ишью не пропадало можно поправить уголки в раскрытом виде)
![image](https://user-images.githubusercontent.com/16453186/56482891-b306b280-64f0-11e9-98bf-34a21890fc9f.png)
