### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by alextsk** [MorganaLF/FlatUI#9]
если посмотреть в макете имена слоев, то понятно что это не три разных кнопки а три состояния одной

**Comment by MorganaLF** [comment]
![FORM](https://user-images.githubusercontent.com/38564412/56651430-acfc0780-6691-11e9-9ad9-c7c4304cf9d8.jpg)
![MESSAGING](https://user-images.githubusercontent.com/38564412/56651431-acfc0780-6691-11e9-9871-8411b72554e9.jpg)

А вот в этих блоках это по идее состояние inactive, хотя в блоке buttons оно указано, как hovered. То есть, получается, что в блоке buttons такая полностью зеленая кнопка будет в состоянии hovered, а в блоках messaging и form те же стили окажутся в модификаторе и это будет как-то странно).

**Comment by alextsk** [comment]
такой макет, приближенный к реальности, наверное) модификатор это нормально

**Comment by alextsk** [comment]
кнопки теперь залипают при нажатии

**Comment by MorganaLF** [comment]
Это стили для фокуса остаются после нажатия. Их убрать?

**Comment by alextsk** [comment]
конечно) очень странно выглядит

**Comment by MorganaLF** [comment]
Исправила.

**Comment by alextsk** [comment]
js тут не нужен, повесь просто их на hover и active.

при множестве кликов на кнопку риппл эффекты должны следовать друг за другом, как круги на воде. сейчас только один эффект

**Comment by MorganaLF** [comment]
А как быть со стилями для :focus на элементе? По стандартам стили для :focus обязательны, но мне непонятно, как они тут должны выглядеть.

**Comment by alextsk** [comment]
можно оставить стандартные, или легкую рамку
